In [1]:
import re
import numpy as np
from PIL import Image
print("Huffman Compression Program")
print("=================================================================")
h = int(input("Enter 1 if you want to input an colour image file, 2 for default gray scale case:"))
if h == 1:
    file = input("Enter the filename:")
    my_string = np.asarray(Image.open(file),np.uint8)
    shape = my_string.shape
    a = my_string
    print ("Enetered string is:",my_string)
    my_string = str(my_string.tolist())
elif h == 2:
    array = np.arange(0, 737280, 1, np.uint8)
    my_string = np.reshape(array, (1024, 720))
    print ("Enetered string is:",my_string)
    a = my_string
    my_string = str(my_string.tolist())

else:
    print("You entered invalid input")

Huffman Compression Program
Enter 1 if you want to input an colour image file, 2 for default gray scale case:1
Enter the filename:Screenshot (79).png
Enetered string is: [[[117 117 117 255]
  [117 117 117 255]
  [117 117 117 255]
  ...
  [230 230 230 255]
  [231 231 231 255]
  [232 232 232 255]]

 [[238 244 249 255]
  [238 244 249 255]
  [238 244 249 255]
  ...
  [230 230 230 255]
  [230 230 230 255]
  [231 231 231 255]]

 [[238 244 249 255]
  [238 244 249 255]
  [238 244 249 255]
  ...
  [229 229 229 255]
  [230 230 230 255]
  [231 231 231 255]]

 ...

 [[240 240 240 255]
  [240 240 240 255]
  [240 240 240 255]
  ...
  [213 213 213 255]
  [214 214 214 255]
  [215 215 215 255]]

 [[240 240 240 255]
  [240 240 240 255]
  [240 240 240 255]
  ...
  [213 213 213 255]
  [214 214 214 255]
  [215 215 215 255]]

 [[240 240 240 255]
  [240 240 240 255]
  [240 240 240 255]
  ...
  [213 213 213 255]
  [214 214 214 255]
  [215 215 215 255]]]


In [2]:
letters = []
only_letters = []
for letter in my_string:
    if letter not in letters:
        frequency = my_string.count(letter)             #frequency of each letter repetition
        letters.append(frequency)
        letters.append(letter)
        only_letters.append(letter)

nodes = []
while len(letters) > 0:
    nodes.append(letters[0:2])
    letters = letters[2:]                               # sorting according to frequency
nodes.sort()
huffman_tree = []
huffman_tree.append(nodes)   

In [3]:
def combine_nodes(nodes):
    pos = 0
    newnode = []
    if len(nodes) > 1:
        nodes.sort()
        nodes[pos].append("1")                       # assigning values 1 and 0
        nodes[pos+1].append("0")
        combined_node1 = (nodes[pos] [0] + nodes[pos+1] [0])
        combined_node2 = (nodes[pos] [1] + nodes[pos+1] [1])  # combining the nodes to generate pathways
        newnode.append(combined_node1)
        newnode.append(combined_node2)
        newnodes=[]
        newnodes.append(newnode)
        newnodes = newnodes + nodes[2:]
        nodes = newnodes
        huffman_tree.append(nodes)
        combine_nodes(nodes)
    return huffman_tree  

In [4]:
newnodes = combine_nodes(nodes)

huffman_tree.sort(reverse = True)
print("Huffman tree with merged pathways:")

checklist = []
for level in huffman_tree:
    for node in level:
        if node not in checklist:
            checklist.append(node)
        else:
            level.remove(node)
count = 0
for level in huffman_tree:
    print("Level", count,":",level)             #print huffman tree
    count+=1
print()


Huffman tree with merged pathways:
Level 0 : [[18981467, ',[]1478963052 ']]
Level 1 : [[7473145, ',[]14789630', '1'], [11508322, '52 ', '0']]
Level 2 : [[4732653, '5', '1'], [6775669, '2 ', '0']]
Level 3 : [[3567071, ',', '1'], [3906074, '[]14789630', '0'], [6775669, '2 ', '0']]
Level 4 : [[3208598, '2', '1'], [3567071, ' ', '0'], [3906074, '[]14789630', '0']]
Level 5 : [[1785574, '[]', '1'], [2120500, '14789630', '0'], [3567071, ' ', '0'], [4732653, '5', '1']]
Level 6 : [[901996, '14', '1'], [1218504, '789630', '0'], [3208598, '2', '1'], [3567071, ',', '1']]
Level 7 : [[892787, '[', '1'], [892787, ']', '0'], [1218504, '789630', '0'], [3567071, ' ', '0'], [4732653, '5', '1']]
Level 8 : [[582180, '78963', '1'], [636324, '0', '0'], [892787, ']', '0'], [3208598, '2', '1'], [3567071, ',', '1']]
Level 9 : [[387948, '1', '1'], [514048, '4', '0'], [636324, '0', '0'], [892787, ']', '0'], [3567071, ' ', '0'], [4732653, '5', '1']]
Level 10 : [[252815, '7', '1'], [329365, '8963', '0'], [514048, '

In [5]:
letter_binary = []
if len(only_letters) == 1:
    lettercode = [only_letters[0], "0"]
    letter_binary.append(letter_code*len(my_string))
else:
    for letter in only_letters:
        code =""
        for node in checklist:
            if len (node)>2 and letter in node[1]:           #genrating binary code
                code = code + node[2]
        lettercode =[letter,code]
        letter_binary.append(lettercode)
print(letter_binary)
print("Binary code generated:")
for letter in letter_binary:
    print(letter[0], letter[1])

[['[', '1011'], ['1', '10011'], ['7', '100011'], [',', '11'], [' ', '000'], ['2', '001'], ['5', '01'], [']', '1010'], ['9', '10001010'], ['3', '10001000'], ['0', '10000'], ['8', '10001011'], ['4', '10010'], ['6', '10001001']]
Binary code generated:
[ 1011
1 10011
7 100011
, 11
  000
2 001
5 01
] 1010
9 10001010
3 10001000
0 10000
8 10001011
4 10010
6 10001001


In [7]:
bitstring =""
for character in my_string:
    for item in letter_binary:
        if character in item:
            bitstring = bitstring + item[1]
binary ="0b"+bitstring
print("Your message as binary is:")
                                        # binary code generated

uncompressed_file_size = len(my_string)*7
compressed_file_size = len(binary)-2
print("Your original file size was", uncompressed_file_size,"bits. The compressed size is:",compressed_file_size)
print("This is a saving of ",uncompressed_file_size-compressed_file_size,"bits")
output = open("compressed.txt","w+")
print("Compressed file generated as compressed.txt")
output = open("compressed.txt","w+")
output

Your message as binary is:
Your original file size was 132870269 bits. The compressed size is: 55912161
This is a saving of  76958108 bits
Compressed file generated as compressed.txt


<_io.TextIOWrapper name='compressed.txt' mode='w+' encoding='cp1252'>

In [8]:
print("Decoding.......")
output.write(bitstring)

bitstring = str(binary[2:])
uncompressed_string =""
code =""
for digit in bitstring:
    code = code+digit
    pos=0                                        #iterating and decoding
    for letter in letter_binary:
        if code ==letter[1]:
            uncompressed_string=uncompressed_string+letter_binary[pos] [0]
            code=""
        pos+=1

Decoding.......


In [9]:
print("Your UNCOMPRESSED data is:")
if h == 1:
    temp = re.findall(r'\d+', uncompressed_string)
    res = list(map(int, temp))
    res = np.array(res)
    res = res.astype(np.uint8)
    res = np.reshape(res, shape)
    print(res)
    print("Observe the shapes and input and output arrays are matching or not")
    print("Input image dimensions:",shape)
    print("Output image dimensions:",res.shape)
    data = Image.fromarray(res)
    data.save('uncompressed.png')
    if a.all() == res.all():
        print("Success")
if h == 2:
    temp = re.findall(r'\d+', uncompressed_string)
    res = list(map(int, temp))
    print(res)
    res = np.array(res)
    res = res.astype(np.uint8)
    res = np.reshape(res, (1024, 720))
    print(res)
    data = Image.fromarray(res)
    data.save('uncompressed.png')
    print("Success")

Your UNCOMPRESSED data is:
[[[117 117 117 255]
  [117 117 117 255]
  [117 117 117 255]
  ...
  [230 230 230 255]
  [231 231 231 255]
  [232 232 232 255]]

 [[238 244 249 255]
  [238 244 249 255]
  [238 244 249 255]
  ...
  [230 230 230 255]
  [230 230 230 255]
  [231 231 231 255]]

 [[238 244 249 255]
  [238 244 249 255]
  [238 244 249 255]
  ...
  [229 229 229 255]
  [230 230 230 255]
  [231 231 231 255]]

 ...

 [[240 240 240 255]
  [240 240 240 255]
  [240 240 240 255]
  ...
  [213 213 213 255]
  [214 214 214 255]
  [215 215 215 255]]

 [[240 240 240 255]
  [240 240 240 255]
  [240 240 240 255]
  ...
  [213 213 213 255]
  [214 214 214 255]
  [215 215 215 255]]

 [[240 240 240 255]
  [240 240 240 255]
  [240 240 240 255]
  ...
  [213 213 213 255]
  [214 214 214 255]
  [215 215 215 255]]]
Observe the shapes and input and output arrays are matching or not
Input image dimensions: (1018, 876, 4)
Output image dimensions: (1018, 876, 4)
Success
